language: julia

os:
  - osx

julia:
  - 0.6

matrix:
  allow_failures:
    julia: nightly

notifications:
  email: false

branches:
  only:
  - master

#script:
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'Pkg.clone(pwd())'
#  - julia -e 'Pkg.test("ABC",coverage=true)'

after_success:
  - julia -e 'Pkg.add("Documenter"); cd(Pkg.dir("ABC")); include(joinpath("docs", "make.jl"))'
  - julia -e 'cd(Pkg.dir("ABC")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
#  - julia -e 'cd(Pkg.dir("ABC")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
